// window.Concerts — shared concert-program data for the schedule (concert cards + program links)
// and concerts.html (the full listing). Hand-transcribed from the PDFs in programs/ (titles in
// English; a -draft pdf keeps the red DRAFT tag until the final lands — then repoint `pdf` and bump
// sw.js V). Each performer is [name-as-printed, instrument] — names reconcile to the roster at
// runtime (no phone numbers here, per the PII rule). Instruments: vn va vc bass pf cl ob + voices.
(() => {
const C = [
 {id:"2026-07-04-aft", title:"Afternoon Concert", day:"Saturday, July 4", time:"4:30 pm",
  venue:"Kultursaal", poi:"Kultursaal", pdf:"programs/2026-07-04-afternoon.pdf", pieces:[
  {c:"Fauré", t:"Piano Quartet No. 1 in C minor, Op. 15", m:"I. Allegro molto moderato",
   who:[["Claudia Ajmone-Marsan","vn"],["Jason Sundram","va"],["Max Buck","vc"],["Mark Zang","pf"]]},
  {c:"Schumann", t:"Piano Trio No. 2 in F major, Op. 80", m:"I. Sehr lebhaft",
   who:[["Nathan Meltzer","vn"],["Richard Beales","vc"],["Felicia Weiss","pf"]]},
  {c:"Larsen", t:"Four on the Floor", m:"",
   who:[["Melody Steinbart","vn"],["Seah Yu","vc"],["Bruce Rosenblum","bass"],["Mark Zang","pf"]]},
  {c:"Brahms", t:"String Quintet No. 2 in G major, Op. 111", m:"I. Allegro non troppo, ma con brio",
   who:[["Ingrid Burger","vn"],["Elinor Turner","vn"],["Emi Ohi Resnick","va"],["Michael Lee","va"],["Stephanie Wingfield","vc"]]},
  {brk:1},
  {c:"Shostakovich", t:"String Quartet No. 9, Op. 117", m:"V. Allegro",
   who:[["Ingrid Burger","vn"],["Maya Weil","vn"],["Angelina Freeman","va"],["David Goldesgeyme","vc"]]},
  {c:"Casarrubios", t:"luzAzul", m:"",
   who:[["Claire Maugham","vn"],["Aaron Kinghorn","vc"],["Kian Woo","pf"]]},
  {c:"Brahms", t:"String Sextet No. 1 in B-flat major, Op. 18", m:"I. Allegro ma non troppo",
   who:[["Korn Roongruangchai","vn"],["YooJin Jang","vn"],["Xinyuan Wang","va"],["Angelina Freeman","va"],["Richard Beales","vc"],["Aaron Kinghorn","vc"]]},
 ]},
 {id:"2026-07-04-eve", title:"Evening Concert", day:"Saturday, July 4", time:"8:00 pm",
  venue:"Pfarrkirche St. Nikolaus", poi:"Pfarrkirche Hl. Nikolaus", pdf:"programs/2026-07-04-evening.pdf", pieces:[
  {c:"Shostakovich", t:"String Quartet No. 8 in C minor, Op. 110", m:"I. Largo · II. Allegro molto",
   who:[["Jane Givens","vn"],["Aafke Koffeman","vn"],["Gijs Kramers","va"],["Richard Beales","vc"]]},
  {c:"Grieg", t:"String Quartet in G minor, Op. 27", m:"II. Romance: Andantino – Allegro agitato",
   who:[["Elinor Turner","vn"],["Chia-Hsuan Lin","vn"],["Joseph Steinbart","va"],["Max Buck","vc"]]},
  {c:"Bacewicz", t:"Quartet for Four Violins", m:"I. Allegretto · II. Andante tranquillo",
   who:[["Elinor Turner","vn"],["Ingrid Burger","vn"],["Tanya Jenkin","vn"],["Claudia Ajmone-Marsan","vn"]]},
  {c:"Vokalensemble Singmazomm", t:"Alpine songs — O sei gegrüßt Maria · Maria hell leuchtender Stern · Zwischen Himmel und Erde · Trag mi Wind · Abendstimmung", m:"",
   who:[["Maria Wendlinger","soprano"],["Gabi Engeler","alto"],["Alois Wendlinger","tenor"],["Lukas Kollnig","bass"]]},
  {brk:1},
  {c:"Haydn", t:"String Quartet in G major, Op. 76 No. 1", m:"II. Adagio sostenuto · III. Menuetto. Presto",
   who:[["Jisoo Kim","vn"],["Claire Maugham","vn"],["Xinyuan Wang","va"],["Preetcharn Saund","vc"]]},
  {c:"Mozart · Mendelssohn", t:"Ave verum corpus · Wirf dein Anliegen auf den Herrn — with Vokalensemble Singmazomm", m:"",
   who:[["Korn Roongruangchai","vn"],["Chia-Hsuan Lin","vn"],["Adam Clarke","va"],["David Goldesgeyme","vc"]]},
  {c:"Debussy", t:"String Quartet in G minor, Op. 10", m:"I. Animé et très décidé",
   who:[["Jane Givens","vn"],["Claudia Ajmone-Marsan","vn"],["Angelina Freeman","va"],["Seah Yu","vc"]]},
 ]},
 {id:"2026-07-08-eve", title:"Faculty Concert", day:"Wednesday, July 8", time:"8:00 pm",
  venue:"Kultursaal", poi:"Kultursaal", pdf:"programs/2026-07-08-evening.pdf", pieces:[
  {c:"Mendelssohn", t:"String Quintet No. 2 in B-flat major, Op. 87", m:"I. Allegro vivace · II. Andante scherzando · III. Adagio e lento · IV. Allegro molto vivace",
   who:[["YooJin Jang","vn"],["Emi Ohi Resnick","vn"],["Ilinca Forna","va"],["Gijs Kramers","va"],["Jesús Morales","vc"]]},
  {c:"Austrian folk song, arr. Stephen Buck", t:"In die Berg bin i gern", m:"",
   who:[["Nikolaus Lanner sen.","flugelhorn"],["Robert Lexer","flugelhorn"],["Roman Cecco","flugelhorn"],["Nathan Meltzer","vn"],["Ilinca Forna","vn"],["Gijs Kramers","va"],["Jesús Morales","vc"]]},
  {c:"Kühr", t:"Portraits", m:"",
   who:[["Jesús Morales","vc"],["Stephen Buck","pf"]]},
  {c:"arr. Gijs Kramers", t:"Songs: Sammy · Ozean · Sternenstaub · Sie glaubt an mich · Schwarz-Weiß", m:"Ramses Shaffy · Racoon · André Hazes · De Jeugd van Tegenwoordig · Frank Boeijen",
   who:[["Ilinca Forna","vn"],["Gijs Kramers","va"],["Jesús Morales","vc"],["Stephen Buck","pf"]]},
 ]},
 {id:"2026-07-09-eve", title:"Evening Concert", day:"Thursday, July 9", time:"8:00 pm",
  venue:"Kultursaal", poi:"Kultursaal", pdf:"programs/2026-07-09-evening-draft.pdf", pieces:[
  {c:"Mozart", t:"Clarinet Quintet in A major, K. 581", m:"I. Allegro",
   who:[["Robert Dembo","cl"],["Aafke Koffeman","vn"],["Tanya Jenkin","vn"],["Isadora Banyai","va"],["Jesús Morales","vc"]]},
  {c:"Coleridge-Taylor", t:"Clarinet Quintet in F-sharp minor, Op. 10", m:"IV. Finale. Allegro agitato",
   who:[["Will Belden","cl"],["Cara Wunder","vn"],["Bernhard Zojer","vn"],["Xinyuan Wang","va"],["Jesús Morales","vc"]]},
  {c:"Jacob", t:"Oboe Quartet", m:"I. Allegro moderato",
   who:[["Chia-Hsuan Lin","vn"],["Michael Lee","va"],["Sara Phelps","vc"],["Katrina Cooper-Strich","ob"]]},
  {c:"Korngold", t:"Suite for Two Violins, Cello and Piano (left hand), Op. 23", m:"I. Prelude and Fugue · IV. Lied",
   who:[["Melody Steinbart","vn"],["Jane Givens","vn"],["Yoanna Prodanova","vc"],["Felicia Weiss","pf"]]},
  {c:"Elgar", t:"Piano Quintet in A minor, Op. 84", m:"I. Moderato – Allegro",
   who:[["Claire Maugham","vn"],["Chia-Hsuan Lin","vn"],["Gijs Kramers","va"],["Stephanie Wingfield","vc"],["Kian Woo","pf"]]},
  {brk:1},
  {c:"Ravel", t:"Piano Trio in A minor, M. 67", m:"I. Modéré",
   who:[["Matthew Chan","vn"],["Alison Atkinson","vc"],["James Cheung","pf"]]},
  {c:"Beethoven", t:"Piano Trio No. 6 in E-flat major, Op. 70 No. 2", m:"I. Poco sostenuto – Allegro ma non troppo",
   who:[["Stephen Lustig","vn"],["Jesús Morales","vc"],["Anne Schoemaker","pf"]]},
  {c:"Brahms", t:"String Quartet No. 3 in B-flat major, Op. 67", m:"I. Vivace",
   who:[["Nathan Meltzer","vn"],["Stephen Lustig","vn"],["Joseph Steinbart","va"],["Seah Yu","vc"]]},
  {c:"Bruch", t:"String Octet in B-flat major, Op. posth.", m:"I. Allegro moderato",
   who:[["Nathan Meltzer","vn"],["Aafke Koffeman","vn"],["Bernhard Zojer","vn"],["Tanya Jenkin","vn"],["Gijs Kramers","va"],["Jason Sundram","va"],["Aaron Kinghorn","vc"],["Bruce Rosenblum","bass"]]},
 ]},
 {id:"2026-07-10-eve", title:"Evening Concert", day:"Friday, July 10", time:"8:00 pm",
  venue:"Kultursaal", poi:"Kultursaal", pdf:"programs/2026-07-10-evening-draft.pdf", pieces:[
  {c:"Ravel", t:"String Quartet in F major, M. 35", m:"I. Allegro moderato – très doux",
   who:[["YooJin Jang","vn"],["Jisoo Kim","vn"],["Ilinca Forna","va"],["David Goldesgeyme","vc"]]},
  {c:"Hindemith", t:"Clarinet Quartet", m:"I. Mäßig bewegt",
   who:[["Sharayu Gugnani","vn"],["Preetcharn Saund","vc"],["Daniel Compton","pf"],["Chad Burrow","cl"]]},
  {c:"Arensky", t:"String Quartet No. 2 in A minor", m:"V. Allegro",
   who:[["Maya Weil","vn"],["Emi Ohi Resnick","vn"],["Valerie Ross","vc"],["Stephanie Wingfield","vc"]]},
  {c:"Schumann", t:"Piano Quartet in E-flat major, Op. 47", m:"I. Sostenuto assai – Allegro ma non troppo",
   who:[["Korn Roongruangchai","vn"],["Joseph Steinbart","va"],["Stephanie Wingfield","vc"],["Anne Schoemaker","pf"]]},
  {c:"Brahms", t:"Piano Quartet No. 1 in G minor, Op. 25", m:"I. Allegro",
   who:[["Jane Givens","vn"],["Jason Sundram","va"],["Preetcharn Saund","vc"],["Mark Zang","pf"]]},
  {brk:1},
  {c:"Beach", t:"Piano Quintet in F-sharp minor, Op. 67", m:"II. Adagio espressivo",
   who:[["Matthew Chan","vn"],["Maya Weil","vn"],["Adam Clarke","va"],["Yoanna Prodanova","vc"],["Tanya Bannister","pf"]]},
  {c:"Beethoven", t:"String Trio in C minor, Op. 9 No. 3", m:"II. Adagio con espressione · III. Scherzo. Allegro molto e vivace",
   who:[["Bernhard Zojer","vn"],["Ilinca Forna","va"],["Valerie Ross","vc"]]},
  {c:"Stravinsky", t:"The Soldier's Tale (Histoire du soldat)", m:"Marche du Soldat · Le violon du Soldat · Petit Concert · Danse du Diable",
   who:[["Chad Burrow","cl"],["Adriana Stamile","vn"],["Mark Zang","pf"]]},
  {c:"Brahms", t:"Clarinet Quintet in B minor, Op. 115", m:"I. Allegro",
   who:[["Chad Burrow","cl"],["Cara Wunder","vn"],["Adriana Stamile","vn"],["Ilinca Forna","va"],["Max Buck","vc"]]},
 ]},
 {id:"2026-07-11-morn", title:"Morning Concert", day:"Saturday, July 11", time:"11:00 am",
  venue:"Kultursaal", poi:"Kultursaal", pdf:"programs/2026-07-11-morning-draft.pdf", pieces:[
  {c:"Haydn", t:"String Quartet in F minor, Op. 20 No. 5", m:"I. Allegro moderato",
   who:[["YooJin Jang","vn"],["Maya Weil","vn"],["Xinyuan Wang","va"],["Sara Phelps","vc"]]},
  {c:"Prokofiev", t:"Quintet in G minor, Op. 39", m:"I. Tema con variazioni · VI. Andantino",
   who:[["Korn Roongruangchai","vn"],["Emi Ohi Resnick","va"],["Will Belden","cl"],["Katrina Cooper-Strich","ob"],["Bruce Rosenblum","bass"]]},
  {c:"Kodály", t:"Serenade for Two Violins and Viola, Op. 12", m:"III. Vivo",
   who:[["Jane Givens","vn"],["Aafke Koffeman","vn"],["Gijs Kramers","va"]]},
  {c:"Brahms", t:"Clarinet Trio in A minor, Op. 114", m:"I. Allegro",
   who:[["Robert Dembo","cl"],["David Goldesgeyme","vc"],["James Cheung","pf"]]},
  {brk:1},
  {c:"Dvořák", t:"Piano Quintet No. 2 in A major, Op. 81", m:"II. Dumka: Andante con moto",
   who:[["Korn Roongruangchai","vn"],["Melody Steinbart","vn"],["Adam Clarke","va"],["Alison Atkinson","vc"],["James Cheung","pf"]]},
  {c:"Loeffler", t:"Two Rhapsodies for Oboe, Viola and Piano", m:"II. La cornemuse",
   who:[["Katrina Cooper-Strich","ob"],["Isadora Banyai","va"],["Kian Woo","pf"]]},
  {c:"Shostakovich", t:"Five Pieces for Two Violins and Piano", m:"Prelude · Gavotte · Elegy · Waltz · Polka",
   who:[["Tanya Jenkin","vn"],["Nathan Meltzer","vn"],["Stephen Buck","pf"]]},
  {c:"Mendelssohn", t:"String Quintet No. 2 in B-flat major, Op. 87", m:"I. Allegro vivace",
   who:[["Claire Maugham","vn"],["Chia-Hsuan Lin","vn"],["Emi Ohi Resnick","va"],["Michael Lee","va"],["Stephanie Wingfield","vc"]]},
 ]},
];
// the schedule (app.js timeline) and concerts.html both read `all` and filter by `c.id`'s date
// prefix, placing each card at its own printed `time` — so a concert renders whether or not the
// day's sheet tab carries a CONCERT banner, and a banner's own (sometimes 12h) time can't misfile it.
window.Concerts = { all: C };
})();
